name: push_nuget

# on manual click
on:
  workflow_dispatch:
    inputs:
      buildnumberMaj:
        description: 'Major Version'     
        required: true
        default: '0'
      buildnumber:
        description: 'Version'     
        required: true
        default: '1'                  
      buildnumberMin:
        description: 'Minor Version'     
        required: true
        default: '0'
      deploy:
          description: 'really push to nuget.org'
          required: false
          type: boolean

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
    - name: report version
      run: echo "${{ github.event.inputs.buildnumberMaj }}.${{ github.event.inputs.buildnumber }}.${{ github.event.inputs.buildnumberMin }}"

    - name: Git Checkout
      uses: actions/checkout@main

    - name: deploy
      if: ${{ github.event.inputs.deploy == 'true' }}
      run: echo "actually deploying..."

    - name: Setup Nuget.exe
      if: ${{ github.event.inputs.deploy == 'true' }}
      uses: nuget/setup-nuget@v2.0.0

    - name: Publish VL Nuget
      if: ${{ github.event.inputs.deploy == 'true' }}
      uses: vvvv/PublishVLNuget@1.0.43
      with:
        # csproj: src\VL.SmallestCircleUtils.csproj

        nuspec: deployment\VL.SmallestCircle.nuspec
        version: ${{ github.event.inputs.buildnumberMaj }}.${{ github.event.inputs.buildnumber }}.${{ github.event.inputs.buildnumberMin }}
        
        icon-src: https://raw.githubusercontent.com/vvvv/PublicContent/master/nugeticon.png
        icon-dst: ./deployment/nugeticon.png
        
        nuget-key: ${{ secrets.NUGET_KEY }}

    # - name: Add msbuild to PATH
    #   uses: microsoft/setup-msbuild@v1.0.2

    # - name: Setup .NET Core SDK
    #   uses: actions/setup-dotnet@v1.4.0
  
    # - name: Build
    #   run: msbuild src\SmallestCircle.sln /t:Build /v:m /m /restore /p:Configuration=Release 
